language: python
python:
    - "2.7"
    - "3.4"
sudo: required
# command to install dependencies
before-install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libhdf5-serial-dev
    - wget https://github.com/Unidata/netcdf-c/archive/v4.3.3.1.tar.gz
    - tar -xvf v4.3.3.1.tar.gz
    - cd netcdf-c-4.3.3.1/
    - ./configure --prefix=/usr/local --disable-netcdf-4
    - make
    - make check
    - make install
    - make uninstall
    - make install
env:
    - NETCDF4_DIR='/usr/bin/local'
install:
    - "pip install -r requirements.txt"
# command to run tests
script: nosetests